name: Bug report
description: File a bug report
title: 'bug: short description'
labels: bug
body:
  - type: textarea
    id: issue-description
    attributes:
      label: (1) Issue/Bug Description/Video Capture/Screenshots
      description: Please describe the issue/bug in detail. Screenshots or screen recordings can be very helpful
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: (2) Steps to reproduce
      description: List the steps to get your problem to happen, if you know them.
      placeholder: "1. Do something\n2. Do something else\n3. Watch your computer go up in flames"
    validations:
      required: false
  - type: textarea
    id: distribution-and-linux-version
    attributes:
      label: (3) Distribution and Linux version
      description: cat /etc/os-release && uname -a
      placeholder: "NAME=\nPRETTY_NAME=\nID=\nBUILD_ID=\nANSI_COLOR=\nHOME_URL=\nDOCUMENTATION_URL=\nSUPPORT_URL=\nBUG_REPORT_URL=\nPRIVACY_POLICY_URL=\nLOGO=\nLinux ..."
      render: shell
    validations:
      required: true
  - type: textarea
    id: journal-logs
    attributes:
      label: (4) Journal Logs from the last hour
      description: journalctl --since='1 hour ago' --follow /usr/bin/gnome-shell
      placeholder: "X 00 00:00:00 x gnome-shell[0000]: x"
      render: shell
    validations:
      required: true
  - type: input
    id: gnome-shell-version
    attributes:
      label: GNOME Shell version
      description: gnome-shell --version
      placeholder: GNOME Shell 00.0
    validations:
      required: true
  - type: input
    id: forge-version
    attributes:
      label: Forge version
      description: Put the extensions.gnome.org version or the commit sha if compiled from source.
      placeholder: "00"
    validations:
      required: true
  - type: textarea
    id: other-extensions
    attributes:
      label: Other installed/enabled extensions
      description: gnome-extensions list --enabled --details
      placeholder: "forge@jmmaranan.com\n	Name: Forge\n	Description: Tiling and window manager for GNOME\n\nPlease report bugs/issues on https://github.com/forge-ext/forge/issues\n	Path: /home/x/.local/share/gnome-shell/extensions/forge@jmmaranan.com\n	URL: https://github.com/forge-ext/forge\n	Version: 00\n	State: ENABLED"
      render: shell
    validations:
      required: true
  - type: textarea
    id: monitor-setup
    attributes:
      label: (6) Monitor Setup
      description: Specifying the monitor/display setup helps a lot for tiling troubleshooting.
      placeholder: "Examples: 2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical)"
    validations:
      required: true
  - type: textarea
    id: other-notes
    attributes:
      label: Other Notes
      description: Anything not covered or N/A
      placeholder: n/a
    validations:
      required: false
