name: Bug Report
description: File a bug report. Add a description after "Bug: "
title: "Bug: "
labels: ["bug"]
body:
  - type: textarea
    id: issue-description
    attributes:
      label: Issue/Bug Description/Video Capture/Screenshots
      description: Please describe the issue/bug in detail. Screenshots, screen recordings, and Extension Manager logs can be very helpful.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: List the steps to get your problem to happen, if you know them.
      placeholder: "1. Do something\n2. Do something else\n3. Watch your computer go up in flames"
    validations:
      required: false
  - type: textarea
    id: distribution-and-linux-version
    attributes:
      label: Distribution and Linux version
      description: Run `cat /etc/os-release && uname -a` and paste the output here.
      placeholder: "NAME=\nPRETTY_NAME=\nID=\nBUILD_ID=\nANSI_COLOR=\nHOME_URL=\nDOCUMENTATION_URL=\nSUPPORT_URL=\nBUG_REPORT_URL=\nPRIVACY_POLICY_URL=\nLOGO=\nLinux ..."
      render: shell
    validations:
      required: true
  - type: textarea
    id: journal-log
    attributes:
      label: Journal Logs from the last hour
      description: Run `journalctl --since='1 hour ago' --follow /usr/bin/gnome-shell` and paste the output here.
      placeholder: "X 00 00:00:00 x gnome-shell[0000]: x"
      render: shell
    validations:
      required: true
  - type: input
    id: gnome-shell-version
    attributes:
      label: GNOME Shell version
      description: Run `gnome-shell --version` and paste the output here.
      placeholder: GNOME Shell 00.0
    validations:
      required: true
  - type: input
    id: forge-version
    attributes:
      label: Forge version
      description: Put the extensions.gnome.org version or the commit sha if compiled from source.
      placeholder: "00"
    validations:
      required: true
  - type: textarea
    id: other-extensions
    attributes:
      label: Other installed/enabled extensions
      description: Run `gnome-extensions list --enabled --details` and paste the output here.
      placeholder: "forge@jmmaranan.com\n	Name: Forge\n	Description: Tiling and window manager for GNOME\n\nPlease report bugs/issues on https://github.com/forge-ext/forge/issues\n	Path: /home/x/.local/share/gnome-shell/extensions/forge@jmmaranan.com\n	URL: https://github.com/forge-ext/forge\n	Version: 00\n	State: ENABLED"
      render: shell
    validations:
      required: true
  - type: textarea
    id: monitor-setup
    attributes:
      label: Monitor Setup
      description: Specifying the monitor/display setup helps a lot for tiling troubleshooting.
      placeholder: "Examples: 2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical)"
    validations:
      required: true
  - type: textarea
    id: other-notes
    attributes:
      label: Other Notes
      description: Anything else you want to add.
    validations:
      required: false
